export const FETCH_TOURS_SUCCESS = "FETCH_TOURS_SUCCESS";
export const FETCH_TOURS_ERROR = "FETCH_TOURS_ERROR";

export const FILTER_TITLE = "FILTER_TITLE";
export const CLEAR_FILTER = "CLEAR_FILTER";
